### ISSUE TITLE
[Trace USAGE] 

### ISSUE THREAD

**Issue by liliaoyuan** [david-oswald/sca_optimal_linear_transforms#1]
Hi there! 
Inew here and I got a problem about the conception.

From what I understand, the correlation coefficient in this context refers to the power model (I chose HW) and the real trace. Since the trace points correspond to the time of a CPU running, the leakage point actually maps to the chosen function's (e.g., First round subbytes) period, not just one specific point. This has left me feeling somewhat perplexed.

I encountered some issues when calculating the Pearson correlation, which involved the HW value of (guess key xor plaintext) and the voltage of each point. Unfortunately, the results turned out to be incorrect, and even more puzzling is that I observed 16 different points ranges fluctuating largely (I calculate every bytes seperately). Was that supposed to be just one point?

the trace is like below  and the arrow is where I think the leakage point is.
![Trace](https://github.com/david-oswald/sca_optimal_linear_transforms/assets/34170909/baa6a9f1-6777-4274-b967-d24de12d3099)

**Comment by david-oswald** [comment]
Hi @liliaoyuan, this sounds like a general question about CPA and not specific to this repo, hence closing.

To answer briefly, it is normal that more than one point in the trace leaks, I'd recommend reading the literature in the field, e.g. 

 http://dpabook.iaik.tugraz.at/
